name: Manual workflow
on:
  workflow_dispatch:
jobs:
 greet:
  runs-on: ubuntu-latest
    steps:
    - name: Send greeting
      run: |
       sudo apt update
       sudo apt -y install python3 python3-pip wget
       pip install tbm13-utils
       wget -P ~ https://github.com/harojpgyy/adups-fota/blob/master/ota.py
       Python3 ota.py

