name: Manual workflow

on:
  workflow_dispatch:
  
jobs: 
  run_demo_actions:
    runs-on: ubuntu-latest
    steps: 
     
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
 
      - name: Run
        run: |
         sudo apt install python-pip pip3
         pip install tbm13-utils
         python3 ota.py
