name: Manual workflow

on:
  workflow_dispatch:
  
jobs: 
  run_demo_actions:
    runs-on: ubuntu-latest
    steps: 
     
      - name: Run
        run: |
         sudo apt install python3
         sudo apt install pip
         pip install tbm13-utils
         python3 ota.py
