name: Manual workflow

on:
  workflow_dispatch:
  
jobs: 
  run_demo_actions:
    runs-on: ubuntu-latest
    steps: 
     
      - name: Run
        run: |
         sudo apt install python3
         sudo apt install python3-pip
         pip install tbm13-utils
         wget https://github.com/harojpgyy/Get_adups_fota/blob/master/ota.py -O /home/ota.py
         sudo chmod 777 /home/ota.py
         python3 ota.py
