name: ota

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-20.04
    
    steps:
    - name: Check Out
      uses: actions/checkout@main
      
    - name: Prepare the environment
      run: |
        sudo apt update
        sudo apt -y install python python3 python-pip python3-pip cpio wget
        pip install tbm13-utils   
      
  
    - name: Download file
      run: |
        wget https://github.com/harojpgyy/adups-fota/blob/master/adups_search_updates.py -O ota.py

      
    - name: Start
      run: |
        Python3 ota.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
