name: ota

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-20.04
    
    steps:
    - name: Check Out
      uses: actions/checkout@main
      
    - name: Prepare the environment
      run: |
        sudo apt update
        sudo apt -y install python python3 python-pip python3-pip cpio wget
        pip install tbm13-utils   
        curl http://example.com/file.zip -o file.zip

        
      
    - name: Start
      run: |
        Python3 ota.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
